### ISSUE TITLE
provider-uri, client-id, client-secret must be set

### ISSUE THREAD

**Issue by yongzhang** [mesosphere/traefik-forward-auth#48]
Hi, 

I can't find any docs to start this app, I'm using OpenID Connect of onelogin, defined below envs:
```
        env:
        - name: DEFAULT_PROVIDER
          value: "oidc"
        - name: DOMAIN
          value: "mydomain.com"
        - name: INSECURE_COOKIE
          value: "true"
        - name: COOKIE_DOMAIN
          value: "mydomain.com"
        - name: AUTH_HOST
          value: "auth.mydomain.com"
        - name: LOG_LEVEL
          value: "trace"
        - name: PROVIDERS_OIDC_ISSUER_URL
          value: "issuer_url"
        - name: PROVIDERS_OIDC_CLIENT_ID
          value: "whatever"
        - name: PROVIDERS_OIDC_CLIENT_SECRET
          value: "whatever"
        - name: PROVIDERS_OIDC_RESOURCE
          value: "whatever"
        - name: SECRET
          value: "whatever"
```
I got this:
```
time="2021-10-20T09:29:01Z" level=fatal msg="provider-uri, client-id, client-secret must be set"
```

Please help, thanks.
